### ISSUE TITLE
SyntaxError: Non-ASCII character '\xc3' in file taiga_contrib_slack/__init__.py on line 2, but no encoding declared

### ISSUE THREAD

**Issue by RubenKelevra** [taigaio/taiga-contrib-slack#20]
I tried to install the slack integration, but this failed on the first command:

ruben@lodur:~/taiga-back$ pip install taiga-contrib-slack
Downloading/unpacking taiga-contrib-slack
  Downloading taiga-contrib-slack-0.0.5.tar.gz
  Running setup.py (path:/tmp/pip_build_ruben/taiga-contrib-slack/setup.py) egg_info for package taiga-contrib-slack
    
    Installed /tmp/pip_build_ruben/taiga-contrib-slack/versiontools-1.9.1-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_ruben/taiga-contrib-slack/setup.py", line 33, in <module>
        'Topic :: Internet :: WWW/HTTP',
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 243, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 277, in finalize_options
        ep.load()(self, ep.name, value)
      File "build/bdist.linux-x86_64/egg/versiontools/setuptools_hooks.py", line 64, in version
      File "build/bdist.linux-x86_64/egg/versiontools/__init__.py", line 234, in from_expression
      File "taiga_contrib_slack/__init__.py", line 2
    SyntaxError: Non-ASCII character '\xc3' in file taiga_contrib_slack/__init__.py on line 2, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
    Complete output from command python setup.py egg_info:
    

Installed /tmp/pip_build_ruben/taiga-contrib-slack/versiontools-1.9.1-py2.7.egg

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_ruben/taiga-contrib-slack/setup.py", line 33, in <module>

    'Topic :: Internet :: WWW/HTTP',

  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 243, in __init__

    _Distribution.__init__(self,attrs)

  File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__

    self.finalize_options()

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 277, in finalize_options

    ep.load()(self, ep.name, value)

  File "build/bdist.linux-x86_64/egg/versiontools/setuptools_hooks.py", line 64, in version

  File "build/bdist.linux-x86_64/egg/versiontools/__init__.py", line 234, in from_expression

  File "taiga_contrib_slack/__init__.py", line 2

SyntaxError: Non-ASCII character '\xc3' in file taiga_contrib_slack/__init__.py on line 2, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_ruben/taiga-contrib-slack
Storing debug log for failure in /home/ruben/.pip/pip.log

**Comment by bameda** [comment]
You are using python 2.7 and Taiga only runs with python 3.4+
