### ISSUE TITLE
Python Error with install on Taiga 1.8.0

### ISSUE THREAD

**Issue by gstrodel** [taigaio/taiga-contrib-slack#31]
SyntaxError: Non-ASCII character '\xc3' in file taiga_contrib_slack/__init__.py on line 2, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_taiga/taiga-contrib-slack
Storing debug log for failure in /home/taiga/.pip/pip.log

**Comment by superalex** [comment]
Hello @gstrodel, are you sure you are using python3 in your virtualenv?

**Comment by gstrodel** [comment]
Hello @superalex Running command `python --version` I get v 2.7.6. Again running self-hosted instance of Taiga 1.8.0. Do I need to upgrade my python version to 3?

**Comment by gstrodel** [comment]
@superalex Nevermind...somehow I missed that Python 3.4 is required for Taiga...odd. http://taigaio.github.io/taiga-doc/dist/setup-production.html

One last point, on the image, I also have Python v3.4 installed since `python3 --version` returns python 3.4.0.

Should I just run the SLACK install with a `python3` command?

**Comment by bameda** [comment]
Try with 

```
workon taiga
python --version 
pip install taiga-contrib-slack
```

**Comment by gstrodel** [comment]
`workon taiga
python --version `
Returns Python 3.4.0

Running the rest of the script now.

**Comment by gstrodel** [comment]
`
taiga@ip-172-16-0-13:~$ workon taiga
(taiga)taiga@ip-172-16-0-13:~$ python --version
Python 3.4.0
(taiga)taiga@ip-172-16-0-13:~$ pip install taiga-contrib-slack
Downloading/unpacking taiga-contrib-slack
  Downloading taiga-contrib-slack-0.0.9.tar.gz
  Running setup.py (path:/home/taiga/.virtualenvs/taiga/build/taiga-contrib-slack/setup.py) egg_info for package taiga-contrib-slack
    
    Installed /home/taiga/.virtualenvs/taiga/build/taiga-contrib-slack/versiontools-1.9.1-py3.4.egg
    
    warning: no files found matching 'README.rst'
Downloading/unpacking django==1.8.5 (from taiga-contrib-slack)
  Downloading Django-1.8.5-py2.py3-none-any.whl (6.2MB): 6.2MB downloaded
Installing collected packages: taiga-contrib-slack, django
  Running setup.py install for taiga-contrib-slack
    
    warning: no files found matching 'README.rst'
  Found existing installation: Django 1.7.8
    Uninstalling Django:
      Successfully uninstalled Django
Successfully installed taiga-contrib-slack django
Cleaning up...
`
Install now appears to be working.

However, I am seeing somehting on the migrate command, is this an issue?:
`
(taiga)taiga@ip-172-16-0-13:~/taiga-back$ python manage.py migrate taiga_contrib_slack
Trying import local.py settings...
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 325, in execute
    django.setup()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/apps/config.py", line 112, in create
    mod = import_module(mod_path)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1448, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django_jinja/apps.py", line 2, in <module>
    from django_jinja import base
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django_jinja/base.py", line 12, in <module>
    from django.template import Origin
ImportError: cannot import name 'Origin'
(taiga)taiga@ip-172-16-0-13:~/taiga-back$ python manage.py migrate taiga_contrib_slack
Trying import local.py settings...                                                                     
Traceback (most recent call last):                                                                     
  File "manage.py", line 10, in <module>                                                               
    execute_from_command_line(sys.argv)                                                                
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line                                                                
    utility.execute()                                                                                  
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 325, in execute                                                                                  
    django.setup()                                                                                     
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/__init__.py", line 18, in setup                                                                                                     
    apps.populate(settings.INSTALLED_APPS)                                                             
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/apps/config.py", line 112, in create
    mod = import_module(mod_path)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1448, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django_jinja/apps.py", line 2, in <module>
    from django_jinja import base
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django_jinja/base.py", line 12, in <module>
    from django.template import Origin
ImportError: cannot import name 'Origin'
`

**Comment by gstrodel** [comment]
To clarify (since the code snippet above it not formatting correctly), I am seeing this issue at the end of the migrate command to create the slack table:
`line 12, in <module> from django.template import Origin ImportError: cannot import name 'Origin'`

Is this a problem?

**Comment by bameda** [comment]
Are you using the last stable branch of taiga-front?
Are you setup the new requirements.txt?

**Comment by gstrodel** [comment]
I installed 1.8.0 using the latest copy of taiga-front-dist and taiga-back using the instructions located here: http://taigaio.github.io/taiga-doc/dist/setup-faqs.html#faq-maintain-update. This was at least 2 months ago and Taiga has been very stable since.

We decided to NOT upgrade to 1.9.0 since 1.8.0 has been very well received and stable. However, we recently started using Slack, so I wanted to install the integration plugin.

**Comment by bameda** [comment]
So you have to install the compatible version of the plugin with taiga-1.8

```
pip install taiga-contrib-slack==0.0.8
```

**Comment by gstrodel** [comment]
Yes, it appears that is the issue based on my investigation of the logs...How do I roll back the install of the current version (0.0.8)?

**Comment by bameda** [comment]
with

```
pip install --upgrade taiga-contrib-slack==0.0.8
```

**Comment by gstrodel** [comment]
Thank you @bameda! I've not had a chance to re-try...but hope to revisit after the holidays. Thank you for closing the the issue, I am sure the right pip command will work. :) :+1:
