### ISSUE TITLE
Option to turn off SSL verification

### ISSUE THREAD

**Issue by magikmw** [taigaio/taiga-contrib-slack#45]
I'm having trouble using the slack plugin with self-hosted Rocket.Chat instance (API claimed to be 1:1 with Slack).
After setting both Taiga plugin and Rocket's webhook I'm getting 'oompa loompas couldn't save...' error, 500 error in nginx, and below in gunicorn.stderr.log.

```ERROR:2016-06-27 16:39:01,641: Internal Server Error: /api/v1/slack/1/test
Traceback (most recent call last):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 784, in _validate_conn
    conn.connect()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 252, in connect
    ssl_version=resolved_ssl_version)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/requests/packages/urllib3/util/ssl_.py", line 305, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.4/ssl.py", line 365, in wrap_socket
    _context=self)
  File "/usr/lib/python3.4/ssl.py", line 601, in __init__
    self.do_handshake()
  File "/usr/lib/python3.4/ssl.py", line 828, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 588, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/viewsets.py", line 106, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/views.py", line 446, in dispatch
    response = self.handle_exception(exc)
  File "/home/taiga/taiga-back/taiga/base/api/views.py", line 443, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/taiga_contrib_slack/api.py", line 41, in test
    tasks.test_slackhook(slackhook.url, slackhook.channel)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/celery/local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/taiga_contrib_slack/tasks.py", line 402, in test_slackhook
    _send_request(url, data)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/taiga_contrib_slack/tasks.py", line 44, in _send_request
    requests.post(url, json=data)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/requests/api.py", line 107, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
```

Doing a manual test with curl outputs:

```curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

Sure enough, --insecure works.
Thing is - I'm not going to get a not-self signed CA certificate for our .local domain. Can we get an option to turn off the certificate verification? I know it doesn't make sense for slack, since it's behind https with proper CA certs, but it's much better to turn off verification than run everything on plaintext http (even on local network).

**Comment by magikmw** [comment]
If not a proper tickbox, I'll settle for a line to change in the plugin's code to turn this check off as a kludge for now.

**Comment by jdobber** [comment]
Setting `export CURL_CA_BUNDLE=""` worked for me.

**Comment by Janfy** [comment]
Also works fine for me using taiga docker installation.

Simply add `CURL_CA_BUNDLE` environment variable in `docker-compose.yml` file :

```
x-environment:
  &default-back-environment
  ...
  # Taiga settings
  ...
  CURL_CA_BUNDLE: ""
```
