### ISSUE TITLE
Error upgrading taiga: ImportError: cannot import name 'get_photo_or_gravatar_url'

### ISSUE THREAD

**Issue by bertez** [taigaio/taiga-contrib-slack#50]
Hi, I'm getting this error upgrading taiga to v3.0.

Any help will be appreciated. Thanks.

```
Trying import local.py settings...
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/home/projects/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/projects/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/home/projects/.virtualenvs/taiga/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/projects/.virtualenvs/taiga/lib/python3.4/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/projects/.virtualenvs/taiga/lib/python3.4/site-packages/taiga_contrib_slack/apps.py", line 41, in ready
    from .api import SlackHookViewSet
  File "/home/projects/.virtualenvs/taiga/lib/python3.4/site-packages/taiga_contrib_slack/api.py", line 26, in <module>
    from . import tasks
  File "/home/projects/.virtualenvs/taiga/lib/python3.4/site-packages/taiga_contrib_slack/tasks.py", line 31, in <module>
    from taiga.users.services import get_photo_or_gravatar_url
ImportError: cannot import name 'get_photo_or_gravatar_url'
```

**Comment by bameda** [comment]
Your bug is similar to this one https://github.com/taigaio/taiga-back/issues/832

**Comment by bertez** [comment]
Thank you for your quick reply. 

I already tried that, but I'm getting a recursion error:

```
  File "/home/projects/.virtualenvs/taiga/build/taiga-contrib-slack/versiontools_support.py", line 99, in get_version

    return self.__base.get_version(self)

  File "/home/projects/.virtualenvs/taiga/build/taiga-contrib-slack/versiontools_support.py", line 99, in get_version

    return self.__base.get_version(self)

  File "/home/projects/.virtualenvs/taiga/build/taiga-contrib-slack/versiontools_support.py", line 99, in get_version

    return self.__base.get_version(self)

  File "/home/projects/.virtualenvs/taiga/build/taiga-contrib-slack/versiontools_support.py", line 99, in get_version

    return self.__base.get_version(self)

  File "/home/projects/.virtualenvs/taiga/build/taiga-contrib-slack/versiontools_support.py", line 99, in get_version

    return self.__base.get_version(self)

  File "/home/projects/.virtualenvs/taiga/build/taiga-contrib-slack/versiontools_support.py", line 99, in get_version

    return self.__base.get_version(self)

  File "/home/projects/.virtualenvs/taiga/build/taiga-contrib-slack/versiontools_support.py", line 99, in get_version

    return self.__base.get_version(self)

RuntimeError: maximum recursion depth exceeded

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /home/projects/.virtualenvs/taiga/build/taiga-contrib-slack
Storing debug log for failure in /home/projects/.pip/pip.log
```

**Comment by bameda** [comment]
```
pip install --upgrade pip
```

an then try again

**Comment by bertez** [comment]
Same error, check the complete log:

```
Collecting taiga-contrib-slack
  Using cached taiga-contrib-slack-3.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-6_uyh8wf/taiga-contrib-slack/setup.py", line 31, in <module>
        'Topic :: Internet :: WWW/HTTP',
      File "/usr/lib/python3.4/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/projects/.virtualenvs/taiga/lib/python3.4/site-packages/setuptools/dist.py", line 239, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/home/projects/.virtualenvs/taiga/lib/python3.4/site-packages/setuptools/dist.py", line 264, in fetch_build_eggs
        replace_conflicting=True
      File "/home/projects/.virtualenvs/taiga/lib/python3.4/site-packages/pkg_resources.py", line 580, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/home/projects/.virtualenvs/taiga/lib/python3.4/site-packages/pkg_resources.py", line 818, in best_match
        return self.obtain(req, installer) # try and download/install
      File "/home/projects/.virtualenvs/taiga/lib/python3.4/site-packages/pkg_resources.py", line 830, in obtain
        return installer(requirement)
      File "/home/projects/.virtualenvs/taiga/lib/python3.4/site-packages/setuptools/dist.py", line 314, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/projects/.virtualenvs/taiga/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 593, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/home/projects/.virtualenvs/taiga/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 623, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/home/projects/.virtualenvs/taiga/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 809, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/home/projects/.virtualenvs/taiga/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 1015, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/home/projects/.virtualenvs/taiga/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 1000, in run_setup
        run_setup(setup_script, args)
      File "/home/projects/.virtualenvs/taiga/lib/python3.4/site-packages/setuptools/sandbox.py", line 50, in run_setup
        lambda: execfile(
      File "/home/projects/.virtualenvs/taiga/lib/python3.4/site-packages/setuptools/sandbox.py", line 100, in run
        return func()
      File "/home/projects/.virtualenvs/taiga/lib/python3.4/site-packages/setuptools/sandbox.py", line 52, in <lambda>
        {'__file__':setup_script, '__name__':'__main__'}
      File "/home/projects/.virtualenvs/taiga/lib/python3.4/site-packages/setuptools/compat.py", line 78, in execfile
        exec(compile(source, fn, 'exec'), globs, locs)
      File "setup.py", line 59, in <module>
      File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.4/distutils/dist.py", line 973, in run_command
        cmd_obj.ensure_finalized()
      File "/usr/lib/python3.4/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/home/projects/.virtualenvs/taiga/lib/python3.4/site-packages/setuptools/command/bdist_egg.py", line 104, in finalize_options
        ei_cmd = self.ei_cmd = self.get_finalized_command("egg_info")
      File "/usr/lib/python3.4/distutils/cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/usr/lib/python3.4/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/home/projects/.virtualenvs/taiga/lib/python3.4/site-packages/setuptools/command/egg_info.py", line 66, in finalize_options
        self.egg_version = self.tagged_version()
      File "/home/projects/.virtualenvs/taiga/lib/python3.4/site-packages/setuptools/command/egg_info.py", line 144, in tagged_version
        version = self.distribution.get_version()
      File "/tmp/easy_install-5xkiegw0/versiontools-1.9.1/versiontools/versiontools_support.py", line 99, in get_version
        return self.__base.get_version(self)
      File "/tmp/pip-build-6_uyh8wf/taiga-contrib-slack/versiontools_support.py", line 99, in get_version
        return self.__base.get_version(self)

      **... last 2 lines repeated a zillion times ...**

        return self.__base.get_version(self)
      File "/tmp/pip-build-6_uyh8wf/taiga-contrib-slack/versiontools_support.py", line 99, in get_version
        return self.__base.get_version(self)
    RuntimeError: maximum recursion depth exceeded
```

**Comment by bameda** [comment]
Try to upgrade versiontools too

```
pip install --upgrade versiontools
```

I use this versions:

```
> pip show versiontools
---
Metadata-Version: 2.0
Name: versiontools
Version: 1.9.1
(...)


> pip show pip
---
Metadata-Version: 2.0
Name: pip
Version: 8.1.2
(...)
```

**Comment by bertez** [comment]
It worked!

My module versions are the same as yours now.

Thank you for your help :)

**Comment by bameda** [comment]
you are welcome
