### ISSUE TITLE
Unable to upgrade via pip install

### ISSUE THREAD

**Issue by aufdenpunkt** [taigaio/taiga-contrib-slack#51]
Hey guys,

first … thanks for your great work! I'm really love taiga!

After executing
`pip install --upgrade taiga-contrib-slack`

I get the following error
`RuntimeError: maximum recursion depth exceeded`

Do you have any ideas?

Traceback:
`Traceback (most recent call last):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/pip/req.py", line 1229, in prepare_files
    req_to_install.run_egg_info()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/pip/req.py", line 325, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/pip/util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command python setup.py egg_info failed with error code 1 in /home/taiga/.virtualenvs/taiga/build/taiga-contrib-slack`

**Comment by aufdenpunkt** [comment]
Duplicate of #50
