### ISSUE TITLE
getting error during  pip install taiga-contrib-slack

### ISSUE THREAD

**Issue by woistjadefox** [taigaio/taiga-contrib-slack#58]
Hi there!

When I try to install the contrib module I get this error on the end:

> Collecting
> taiga-contrib-slack
  Using cached taiga-contrib-slack-3.0.2.tar.gz
    Complete output from command python setup.py egg_info:

    Installed /tmp/pip-build-q9MyUN/taiga-contrib-slack/.eggs/versiontools-1.9.1-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-q9MyUN/taiga-contrib-slack/setup.py", line 31, in <module>
        'Topic :: Internet :: WWW/HTTP',
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 272, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 327, in finalize_options
        ep.load()(self, ep.name, value)
      File "build/bdist.linux-x86_64/egg/versiontools/setuptools_hooks.py", line 64, in version
      File "build/bdist.linux-x86_64/egg/versiontools/__init__.py", line 234, in from_expression
      File "/tmp/pip-build-q9MyUN/taiga-contrib-slack/taiga_contrib_slack/__init__.py", line 2
    SyntaxError: Non-ASCII character '\xc3' in file /tmp/pip-build-q9MyUN/taiga-contrib-slack/taiga_contrib_slack/__init__.py on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

>    ----------------------------------------
>Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-q9MyUN/taiga-contrib-slack/

Any idea how I can solve that?
Thanks

**Comment by bameda** [comment]
You are using python 2.7 and I suppose too that your are setup outside the taiga env. 

```
workon taiga
pip install taiga-contrib-slack
```
