### ISSUE TITLE
Taiga leaving user-stories uneditable if slack plugin enabled. 

### ISSUE THREAD

**Issue by couchgott** [taigaio/taiga-contrib-slack#62]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Oops, something happened...
Our Oompa Loompas are sad, your changes were not saved! 

if you try to add an descriptive text to a user-story having related tasks (more than 2). 
We're using 2 additional/custom fields on the user story 

If you try to add an comment to the task the loading circle is constantly spinning but nothing is finally sved. 
**If the current behavior is a bug, please provide the steps to reproduce.**
Create a user story, add some Related Tasks. 

**What is the expected behavior?**
Save the Descriptive text, save the Comment.

**Is it happening in taiga.io or in your own instance?**
own instance. 

**What browser/version are you using?**
FF55, IE11, Chrome 60

**Are there any console errors *(Ctrl + F12)* in red?**
ERROR:2017-08-18 07:38:04,095: Internal Server Error: /api/v1/userstories/14
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/src/taiga-back/taiga/base/api/viewsets.py", line 106, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/src/taiga-back/taiga/base/api/views.py", line 461, in dispatch
    response = self.handle_exception(exc)
  File "/usr/src/taiga-back/taiga/base/api/views.py", line 458, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/src/taiga-back/taiga/base/api/mixins.py", line 207, in partial_update
    return self.update(request, *args, **kwargs)
  File "/usr/src/taiga-back/taiga/projects/userstories/api.py", line 290, in update
    return super().update(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/usr/src/taiga-back/taiga/base/decorators.py", line 60, in decorator
    return func(self, *args, **kwargs)
  File "/usr/src/taiga-back/taiga/base/api/mixins.py", line 200, in update
    self.post_save(self.object, created=False)
  File "/usr/src/taiga-back/taiga/projects/userstories/api.py", line 239, in post_save
    super().post_save(obj, created)
  File "/usr/src/taiga-back/taiga/projects/occ/mixins.py", line 85, in post_save
    super().post_save(obj, created)
  File "/usr/src/taiga-back/taiga/projects/history/mixins.py", line 79, in post_save
    self.persist_history_snapshot(obj=obj)
  File "/usr/src/taiga-back/taiga/projects/history/mixins.py", line 75, in persist_history_snapshot
    self.__last_history = take_snapshot(sobj, comment=comment, user=user, delete=delete)
  File "/usr/local/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/usr/src/taiga-back/taiga/projects/history/services.py", line 369, in take_snapshot
    return entry_model.objects.create(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 399, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 796, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 833, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/usr/local/lib/python3.5/site-packages/django/dispatch/dispatcher.py", line 191, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/local/lib/python3.5/site-packages/taiga_contrib_slack/signal_handlers.py", line 89, in on_new_history_entry
    task(*args)
  File "/usr/local/lib/python3.5/site-packages/celery/local.py", line 191, in __call__
    return self._get_current_object()(*a, **kw)
  File "/usr/local/lib/python3.5/site-packages/celery/app/task.py", line 379, in __call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/taiga_contrib_slack/tasks.py", line 272, in change_slackhook
    attachment = _field_to_attachment(template_field, field_name, values)
  File "/usr/local/lib/python3.5/site-packages/taiga_contrib_slack/tasks.py", line 86, in _field_to_attachment
    change_field_text = template_field.render(context.flatten())
  File "/usr/local/lib/python3.5/site-packages/django_jinja/backend.py", line 106, in render
    return mark_safe(self.template.render(context))
  File "/usr/local/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/site-packages/taiga_contrib_slack/templates/taiga_contrib_slack/field-diff.jinja", line 41, in top-level template code
    *{{ att.name }}:* from *{{ att.changes.value.0 }}* to *{{ att.changes.value.1 }}*
  File "/usr/local/lib/python3.5/site-packages/jinja2/environment.py", line 411, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'value'

thanks :) 

couchgott

**Comment by bameda** [comment]
Are you using the same version for `taiga-back` and `taiga-contrib-slack`?

To taiga-back 
```
cd taiga-back
git describe --tag
```

To taiga-contrib slack
```
workon taiga
pip show taiga-contrib-slack | grep Version 
```

**Comment by couchgott** [comment]
hey bameda,

i am using https://github.com/benhutchins/docker-taiga-example
i cannot git the version inside of the container. but i guess its same (stable) version for both. 
I do have that issue only if you have more than 2 or 3 related tasks at a user story. if you got only 1/2 it's saving fine. 
Also leaving the plugin enable for everything bug "user-story" changes does help as a work-a-round for now (ok, not notifies for changes in user-stories now obviously) 

the Dockerfile installing the Slack Plugin looks like: 

RUN SLACK_VERSION=$(pip show taiga-contrib-slack | awk '/^Version: /{print $2}') && \
    echo "taiga-contrib-slack version: $SLACK_VERSION" && \
    curl https://raw.githubusercontent.com/taigaio/taiga-contrib-slack/$SLACK_VERSION/front/dist/slack.js -o /usr/src/taiga-front-dist/dist/plugins/slack/slack.js && \
    curl https://raw.githubusercontent.com/taigaio/taiga-contrib-slack/$SLACK_VERSION/front/dist/slack.json -o /usr/src/taiga-front-dist/dist/plugins/slack/slack.json

which gives you: 
 pip show taiga-contrib-slack
Name: taiga-contrib-slack
Version: 3.1

Cheers!

**Comment by couchgott** [comment]
Hi,

just one more detail. 
the error also leaves you not capable to edit the user-stories assignment. 

jic
