### ISSUE TITLE
Github integration will be failed after installing slack

### ISSUE THREAD

**Issue by simmytruong** [taigaio/taiga-contrib-slack#71]
Hi,

I recently installed taiga from taiga-scripts repo. My server has been functioning well. 

I setup github integration by using the web GUI, and my server can receive webhook json from github without any issue. For example, If I commit like "Test by me for TG-1" and then, I can see this comment and commit link from github under my ticket (REF = 1).

After that, I installed slack as the guideline [here](https://github.com/taigaio/taiga-contrib-slack/blob/master/README.md). I can see, my taiga server is able to send notifications to slack.

BUT....... The issue happen! After installed taiga-contrib-slack plugin, my taiga server is unable to receive github commit anymore (but it is interesting that I can change ticket status from github, for example: TG-1 #ready), my comment that worked before such as "Test by me for TG-1" will not link to my ticket anymore. And under nginx logs, I can see code 500 returned and gunicorn said Index Group not found or something like that.

So, I would like to have an advice how to figure out the issue. Seems that after install this slack plugin, my github is crashed

Thanks,
Simmy

**Comment by oderwat** [comment]
Adding to OPs comments:

If you enable both: Slack Plugin and GitHub integration the GitHub integration fails inside the Slack code. 

The reason for this is that the comment which is created by the GitHub integration contains both the `'` and `"` delimiters. Slack Plugin uses `from markdown.inlinepatterns import LINK_RE` to obtain the *flawed* regular expression of (an older version) the markdown Python module. 

The markdown module seems to be updated already and does not use such a regular expression for parsing anymore. Afaik the current `LINK_RE` is just a trigger for the beginning of the parser and does a correct parsing of the markdown now.

As this type of comment can also be written by a user it is mandatory for the Slack plugin to be changed to work in a different way. A (crude) temporary solution may be to create another (flawed) regular expression to make *this case* working

Also see https://github.com/taigaio/taiga-back/issues/1106#issuecomment-438725248

**Comment by madmath03** [comment]
For info, this issue also happens with GitLab integration.
The error stack trace looks like this:
```
ERROR:2020-04-16 11:02:01,342: Internal Server Error: /api/v1/gitlab-hook
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/src/taiga-back/taiga/base/api/viewsets.py", line 106, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/src/taiga-back/taiga/base/api/views.py", line 460, in dispatch
    response = self.handle_exception(exc)
  File "/usr/src/taiga-back/taiga/base/api/views.py", line 458, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/src/taiga-back/taiga/hooks/api.py", line 79, in create
    event_hook.process_event()
  File "/usr/src/taiga-back/taiga/hooks/event_hooks.py", line 264, in process_event
    user=self.get_user(commit['user_id'], self.platform_slug))
  File "/usr/local/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/usr/src/taiga-back/taiga/projects/history/services.py", line 422, in take_snapshot
    return entry_model.objects.create(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 394, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 848, in save_base
    update_fields=update_fields, raw=raw, using=using,
  File "/usr/local/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 193, in send
    for receiver in self._live_receivers(sender)
  File "/usr/local/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 193, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/usr/local/lib/python3.6/site-packages/taiga_contrib_slack/signal_handlers.py", line 89, in on_new_history_entry
    task(*args)
  File "/usr/local/lib/python3.6/site-packages/celery/local.py", line 191, in __call__
    return self._get_current_object()(*a, **kw)
  File "/usr/local/lib/python3.6/site-packages/celery/app/task.py", line 394, in __call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/taiga_contrib_slack/tasks.py", line 239, in change_slackhook
    comment = re.sub(LINK_RE, _link_transform, change.comment)
  File "/usr/local/lib/python3.6/re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/local/lib/python3.6/site-packages/taiga_contrib_slack/tasks.py", line 220, in _link_transform
    url_split = match.group(8).split()
IndexError: no such group
```
