### ISSUE TITLE
 Update for Taiga 5.x planned?

### ISSUE THREAD

**Issue by ichasco** [taigaio/taiga-contrib-slack#76]
Hi,

I have tried it in Taiga 5.0.7 and it doesn't work. It's possible to update it to support this version?

Thanks!

**Comment by gramakri** [comment]
This works fine on taiga 5.0 but it's broken on 5.5

**Comment by lesmyrmidons** [comment]
For 5.5.7, the error message :
```
Trying import local.py settings...
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/taiga_contrib_slack/models.py", line 22, in <module>
    class SlackHook(models.Model):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/taiga_contrib_slack/models.py", line 24, in SlackHook
    related_name="slackhooks")
TypeError: __init__() missing 1 required positional argument: 'on_delete'
```

**Comment by migonzalvar** [comment]
Please, update the plugin version to the last one, as of today, 5.5.1. See #79
